name: wrf-xarray

channels:
  - conda-forge

dependencies:
  - python=3.11
  - setuptools<81.0.0
  - xarray
  - dask
  - netcdf4
  - h5netcdf
  - wrf-python
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - jupyterlab
